name: Deploy on gh page

on:
  push:
    branches:
      - main # Set a branch that will trigger a deployment

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Configure Dotenv
        run: |
          echo NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL} >> .env
        env:
          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.THE_MOVIE_DB_API }}

      - name: Build
        run: CI=false npm run build # Using CI=false remove Treat warning as error that make the compilation fail

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: raid-registering.myecl.fr
